### ISSUE TITLE
Theory setup file removes axioms with %

### ISSUE THREAD

**Issue by acchow** [acchow/seadoo#3]
theory_setup.py line 45 removes strings containing % (intended to rm comments but removes whole axioms if the lines are combined)

**Comment by acchow** [comment]
theory_setup.py line 45 removes strings containing % (intended to rm comments but removes whole axioms if the lines are combined)

**Comment by acchow** [comment]
workaround: remove the comments or add . at the end of a comment line

**Comment by selenalombardi** [comment]
note about workaround: refers to comment lines in seadoo/orderings/ontologies files. files should end with .in
